# Site settings
title: "Dmitri Pisarev for The Web!"
email: dimaip@gmail.com
description: "Reflections on modern web development techniques."
baseurl: ""
url: "http://dimaip.tumblr.com"
twitter_username: dimaip
github_username:  dimaip
host: server.psmb.ru

# Build settings
markdown: kramdown
permalink: pretty
